* 开发日记
** <2014-07-24 Thu>
*** DONE 基本的git仓库的建立，以及对git仓库的一些初始化和设置的问题。
CLOSED: [2014-07-29 Tue 21:26]
- State "DONE"       from ""           [2014-07-29 Tue 21:26]
*** DONE 看完了《orange》的第一章
CLOSED: [2014-07-29 Tue 21:26]
- State "DONE"       from ""           [2014-07-29 Tue 21:26]
** <2014-07-29 Tue>
*** DONE 安装bochs和配置bochs
CLOSED: [2014-07-29 Tue 22:40]
- State "DONE"       from "TODO"       [2014-07-29 Tue 22:40]
**** 安装bochs遇到问题
.fatal error: gtk/gtk.h: No such file or directory

solved：
- 将`pkg-config gtk+-2.0 --cflags --lib`添加的到bochs下的Makefile的LIBS变量以及bochs下的gui的下Makefile中的LIBS中
- ./config .....
- make 
- sudo make install

**** bochs的配置
- couldn't open ROM image file '/usr/share/bochs/BIOS-bochs-latest

solution: 
modyfy the bochsrc file
romimage: file=/usr/local/share/bochs/BIOS-bochs-latest

- can not stat keymap file 'usr/share/bochskeymaps/x11-pc-us.map'
solution:
 将bochsrc文件中最后一行keyboard_ mapping: enabled=1, map=/usr/share/bochs/keymaps/x11-pc-us.map改为

              　　keyboard_ mapping: enabled=1, map=/usr/local/share/bochs/keymaps/x11-pc-us.map #/usr/share/bochs/keymaps　　 

  　　　　　  /x11-pc-us.map
*** DONE read the chapter of the book <Orange's>
CLOSED: <2014-07-29 Tue 22:47>
- State "DONE"       from "TODO"       [2014-07-29 Tue 22:47]
主要是看了一些调试常用的命令，这是比较重要的，以后要多用一用。
** <2014-07-30 Wed> 
*** TODO read the book of chapter 3
**** pmtest1.asm 的编写遇到问题。
不能在屏幕上显示红色的“p”
** <2014-08-02 Sat 12:31>
*** 完成dos使用的引导
**** 在下面的网址下载freedos
http://bochs.sourceforge.net/diskimages.html
，然后按照书本上的说明安装一下。

**** 挂载点 /mnt/floppy不存在，
自己创建就可以了，但是要注意，要开着bochs，并且把b，格式化之后才行。
*** 阅读pmtest1.asm
**** 指令EQU 
EQU不是指令集中的指令而是一条伪指令，在程序中多次出现同一个表达式，为了方便，可以用赋值伪操作给表达式赋予一个名字，就叫equ，我的理解就是equ可以类比为C语言中的宏定义。

**** org
汇编语言中的一条指令，作用：告诉汇编程序，在执行的时候，将某段机器语言装载到内存中的哪个地址，也是伪指令
*** 阅读王爽的《汇编语言》<2014-08-02 Sat>--<2014-08-09 Sat>
完成汇编语言的通读一遍